# Generated by Django 3.1.7 on 2022-01-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monday_landing', '0002_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
