# Generated by Django 3.1.7 on 2022-01-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monday_landing', '0005_application_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monday_landing.course'),
        ),
    ]
